name: Run tempest tests

on:
  workflow_call:
    secrets:
      accounts_gpg_passphrase:
        required: true
        description: "gpg passphrase to decrypt openstack credentials"
    inputs:
      config-path:
        required: true
        type: string
        description: "path to dir containing tempest.conf and accounts.yaml.gpg"
      name:
        required: true
        type: string
      tempest_args:
        required: true
        type: string
    outputs:
      subunit_artifact_url: 
        value: "${{ jobs.tempest_action.outputs.subunit_artifact_url }}"
      subunit_artifact_id: 
        value: "${{ jobs.tempest_action.outputs.subunit_artifact_id }}"

jobs:
  tempest_action:
    name: "Tempest Tests: ${{inputs.name}}"
    runs-on: ubuntu-22.04
    outputs:
      subunit_artifact_url: ${{ steps.subunit_artifact.outputs.artifact-url}}
      subunit_artifact_id: ${{ steps.subunit_artifact.outputs.artifact-id}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
          cache: 'pip'
      - name: install tempest
        run: pip install .
      - name: decrypt_accounts_file
        env:
          SECRET_PASSPHRASE: ${{secrets.accounts_gpg_passphrase}}
        run: |
          ./decrypt_secret.sh \
            "${{inputs.config-path}}/accounts.yaml.gpg" \
            "${{inputs.config-path}}/accounts.yaml"
      - name: init workspace from source config
        run: tempest init --config-dir ${{inputs.config-path}} --name ${{inputs.name}} workspace
      - name: show templated config
        run: cat workspace/etc/tempest.conf
      - name: Tempest Run
        working-directory: workspace
        continue-on-error: true
        run: tempest run ${{ inputs.tempest_args }}
      - name: save subunit output
        working-directory: workspace
        run: |
          mkdir subunit_output
          stestr last --all-attachments --subunit > "subunit_output/${{inputs.name}}-${{github.run_id}}.subunit"
          python3 ../src/tempest_runner/parse_results.py . \
          && mv ctrf-results-0.json "subunit_output/${{inputs.name}}-${{github.run_id}}-ctrf.json"
      - name: upload result artifact
        id: subunit_artifact
        uses: actions/upload-artifact@v4
        with:
          path: "workspace/subunit_output"
          name: "${{inputs.name}}.subunit"
