name: run smoke tests for CHI@NU

on: 
  workflow_dispatch:
  schedule:
    - cron: "20 7 * * *"

jobs:
  run_tests:
    name: "CHI@NU Smoke Tests"
    uses: ./.github/workflows/tempest_action.yaml
    with:
      config-path: reference_configs/nu_prod/
      name: "CHI@NU"
    secrets:
      accounts_gpg_passphrase: ${{secrets.accounts_gpg_passphrase}}
      slack_webhook_url: ${{secrets.slack_webhook_url}}
