name: run image smoke tests for KVM@TACC

on:
  workflow_dispatch:
  schedule:
    - cron: "30 7 * * *"
  push:
    branches: main
    paths:
      - reference_configs/kvm_prod/
      - src
      - .github/workflows/tempest_action.yaml
      - .github/workflows/test_kvm_tacc_prod_noncritical.yaml

concurrency:
  group: "KVM@TACC"
  cancel-in-progress: false

jobs:
  critical_tests:
    name: "KVM@TACC Image Tests"
    uses: ./.github/workflows/tempest_action.yaml
    with:
      config-path: reference_configs/kvm_prod/
      name: "KVM@TACC"
      enable_alerts: true
      regex: "blazar_tempest_plugin.tests.scenario.test_images.*(?<!non)critical"
    secrets:
      accounts_gpg_passphrase: ${{secrets.accounts_gpg_passphrase}}
      slack_webhook_url: ${{secrets.slack_webhook_url}}
  noncritical_tests:
    name: "KVM@TACC Image Tests"
    uses: ./.github/workflows/tempest_action.yaml
    with:
      config-path: reference_configs/kvm_prod/
      name: "KVM@TACC"
      enable_alerts: true
      regex: "blazar_tempest_plugin.tests.scenario.test_images.*noncritical"
    secrets:
      accounts_gpg_passphrase: ${{secrets.accounts_gpg_passphrase}}
      slack_webhook_url: ${{secrets.slack_noncritical_webhook_url}}
