name: run smoke tests for CHI@UC

on: 
  workflow_dispatch:
  schedule:
    - cron: "20 7 * * *"
  push:
    branches: main
    paths:
      - reference_configs/uc_prod/
      - src
      - .github/workflows/tempest_action.yaml
      - .github/workflows/test_chi_uc_prod.yaml

jobs:
  run_tests:
    name: "CHI@UC Smoke Tests"
    uses: ./.github/workflows/tempest_action.yaml
    with:
      config-path: reference_configs/uc_prod/
      name: "CHI@UC"
    secrets:
      accounts_gpg_passphrase: ${{secrets.accounts_gpg_passphrase}}
      slack_webhook_url: ${{secrets.slack_webhook_url}}
