name: run smoke tests for DEV@UC

on: 
  workflow_dispatch:

concurrency:
  group: "DEV@UC"
  cancel-in-progress: false

jobs:
  run_tests:
    name: "DEV@UC Smoke Tests"
    uses: ./.github/workflows/tempest_action.yaml
    with:
      config-path: reference_configs/uc_dev/
      name: "DEV@UC"
    secrets:
      accounts_gpg_passphrase: ${{secrets.accounts_gpg_passphrase}}
      slack_webhook_url: ${{secrets.slack_webhook_url}}
